# Use a Node.js base image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to leverage Docker cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Install NestJS CLI globally (if needed)
RUN npm install -g @nestjs/cli

# Copy the rest of your application code
COPY . .

# Expose the port your NestJS app listens on
EXPOSE 3000

# Command to run in development mode with watch
CMD ["npm", "run", "start:dev"]